<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKIk0RzL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKIk0RzL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKIk0RzL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKIk0RzL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKIk0RzL\App_KernelDevDebugContainer([
    'container.build_hash' => 'KIk0RzL',
    'container.build_id' => '4326bc4a',
    'container.build_time' => 1622705540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKIk0RzL');
