<?php

namespace ContainerKIk0RzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3FxqBklService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3FxqBkl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3FxqBkl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'domain' => ['privates', '.errored..service_locator.3FxqBkl.App\\Entity\\Domain', NULL, 'Cannot autowire service ".service_locator.3FxqBkl": it references class "App\\Entity\\Domain" but no such service exists.'],
        ], [
            'domain' => 'App\\Entity\\Domain',
        ]);
    }
}
