<?php

namespace ContainerKIk0RzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPasswordEncoderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pwZ6MTM.Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface' shared service.
     *
     * @return \Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pwZ6MTM": it references interface "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
