<?php

namespace ContainerMw8WTxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0creGmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0creGm_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0creGm_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'question' => ['privates', '.errored..service_locator.0creGm_.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.0creGm_": it references class "App\\Entity\\Question" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.0creGm_.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.0creGm_": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'question' => 'App\\Entity\\Question',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
