<?php

namespace ContainerMw8WTxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VKGz4a5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vKGz4a5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vKGz4a5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tutorial' => ['privates', '.errored..service_locator.vKGz4a5.App\\Entity\\Tutorial', NULL, 'Cannot autowire service ".service_locator.vKGz4a5": it references class "App\\Entity\\Tutorial" but no such service exists.'],
        ], [
            'tutorial' => 'App\\Entity\\Tutorial',
        ]);
    }
}
