<?php

namespace ContainerMw8WTxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthenticationUtilsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UDgw6Ol.Symfony\Component\Security\Http\Authentication\AuthenticationUtils' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticationUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UDgw6Ol": it references class "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils" but no such service exists.');
    }
}
