<?php

namespace ContainerMw8WTxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTutorialService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vKGz4a5.App\Entity\Tutorial' shared service.
     *
     * @return \App\Entity\Tutorial
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vKGz4a5": it references class "App\\Entity\\Tutorial" but no such service exists.');
    }
}
